server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: watchmaster
    password: xxm_123456
    url: jdbc:mysql://pc-wz946m42f47q5f51h.rwlb.rds.aliyuncs.com:3306/watch?useSSL=false&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  redis:
    host: 172.18.68.42
    database: 0
  rabbitmq:
    addresses: 172.18.68.42
    username: admin
    password: KcvnAg_Np2035
    listener:
      simple:
        acknowledge-mode: manual
  freemarker:
    template-loader-path: classpath:/templates/
    enabled: true
    cache: false
    suffix: .ftl
    charset: utf-8
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        format_sql: false
    show-sql: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    mongodb:
      database: watch
      uri: mongodb://172.18.68.42:29998/watch?maxpoolsize=10&minpoolsize=3
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 172.18.68.42:9300
      cluster-name: elasticsearch
  cache:
    type: redis
  elasticsearch:
    uris: http://172.18.68.42:9200
  ftp:
    password: ftp_123_user
    username: ftpUser
    host: 127.0.0.1
    port: 21
  wxpay:
    appid: wx4f8452fef8ffefb7
    apikey: q7XKC4TH5ydVCazZ5WEsmSapdifFDUfq
    mchid: 1622725273
  socketio:
    host: 172.18.68.41
    port: 9099
    maxFramePayloadLength: 1048576
    maxHttpContentLength: 1048576
    bossCount: 1
    workCount: 100
    allowCustomRequests: true
    upgradeTimeout: 1000000
    pingTimeout: 6000000
    pingInterval: 25000
  mail:
    password: Ejcprp335Jxaj
    username: admin@zfbip.com
    host: smtpdm.aliyun.com
    port: 80
    default-encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  session:
    store-type: redis
    timeout: 60m
publish:
  version: 202112011709
scheduling:
  enabled: true
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: INFO
          elasticsearch:
            core: ERROR
    com:
      zhide:
        govwatch:
          mapper: ERROR
  file:
    path: C:\\Log\\
  logback:
    rollingpolicy:
      max-history: 30
      clean-history-on-start: true
      max-file-size: 100MB
  charset:
    file: UTF-8
mybatis:
  type-aliases-package: com.zhide.govwatch.model
  configuration:
    use-actual-param-name: true
  mapper-locations: mybatis/mapper/*.xml
